apiVersion: v1
kind: Secret
data:
  ssh-keyfile: {{ .Values.sshkey }}
metadata:
  name: {{ .Release.Name }}-sshkey
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "junos_exporter.labels" . | nindent 4 }}
type: Opaque